Repository FlexGym/Flex_Gym, pull requests merged in 2023-06, with the labels that each got.

#17 feat/채팅방 유저 나가기 기능 구현
  src/main/java/com/ll/FlexGym/domain/ChatMember/entity/ChatMember.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/entity/ChatRoom.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/service/ChatRoomService.java
  src/main/java/com/ll/FlexGym/domain/Member/entitiy/Member.java
  src/main/resources/static/app.js
  src/main/resources/templates/usr/chat/room.html
Labels: feature

#18 feat/meeting 모임 기능 기초 작업
  src/main/java/com/ll/FlexGym/domain/Meeting/MeetingForm.java
  src/main/java/com/ll/FlexGym/domain/Meeting/controller/MeetingController.java
  src/main/java/com/ll/FlexGym/domain/Meeting/entity/Meeting.java
  src/main/java/com/ll/FlexGym/domain/Meeting/repository/MeetingRepository.java
  src/main/java/com/ll/FlexGym/domain/Meeting/service/MeetingService.java
  src/main/java/com/ll/FlexGym/global/init/NotProd.java
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/meeting/detail.html
  src/main/resources/templates/usr/meeting/form.html
  src/main/resources/templates/usr/meeting/list.html
Labels: feature

#21 Feat/information 기능추가
  build.gradle
  src/main/java/com/ll/FlexGym/domain/Information/controller/InformationController.java
  src/main/java/com/ll/FlexGym/domain/Information/entity/Information.java
  src/main/java/com/ll/FlexGym/domain/Information/repository/InformationRepository.java
  src/main/java/com/ll/FlexGym/domain/Information/service/InformationService.java
  src/main/java/com/ll/FlexGym/domain/youtube/controller/YoutubeController.java
  src/main/java/com/ll/FlexGym/domain/youtube/entity/YoutubeEntity.java
  src/main/java/com/ll/FlexGym/domain/youtube/repository/YoutubeRepository.java
  src/main/java/com/ll/FlexGym/domain/youtube/service/YoutubeService.java
  src/main/resources/templates/usr/information/info.html
Labels: feature

#23 feat/모임과 채팅방 연결
  src/main/java/com/ll/FlexGym/domain/ChatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/entity/ChatRoom.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/service/ChatRoomService.java
  src/main/java/com/ll/FlexGym/domain/Meeting/controller/MeetingController.java
  src/main/java/com/ll/FlexGym/global/init/NotProd.java
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/meeting/detail.html
Labels: feature

#27 Feat/information2
  src/main/java/com/ll/FlexGym/domain/Information/controller/InformationController.java
  src/main/java/com/ll/FlexGym/domain/Information/service/InformationService.java
Labels: feature

#28 feat/meeting-participant 모임 참여자수 증가/제한 기능
  src/main/java/com/ll/FlexGym/domain/ChatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/service/ChatRoomService.java
  src/main/java/com/ll/FlexGym/domain/Meeting/controller/MeetingController.java
  src/main/java/com/ll/FlexGym/domain/Meeting/entity/Meeting.java
  src/main/java/com/ll/FlexGym/domain/Meeting/repository/MeetingRepository.java
  src/main/java/com/ll/FlexGym/domain/Meeting/service/MeetingService.java
  src/main/java/com/ll/FlexGym/global/init/NotProd.java
  src/main/java/com/ll/FlexGym/global/rq/Rq.java
  src/main/resources/templates/usr/meeting/detail.html
Labels: feature

#33 Feat/information3 영상 관리자페이지 구현(bootstrap)
  src/main/java/com/ll/FlexGym/domain/Information/controller/InformationController.java
  src/main/java/com/ll/FlexGym/domain/Information/service/InformationService.java
  src/main/java/com/ll/FlexGym/global/init/NotProd.java
  src/main/resources/templates/usr/information/info.html
Labels: feature

#32 feat/모임을 삭제할 경우 채팅방까지 같이 삭제, 입장 메시지, 채팅방 제목 수정
  src/main/java/com/ll/FlexGym/domain/ChatMessage/controller/ChatMessageController.java
  src/main/java/com/ll/FlexGym/domain/ChatMessage/dto/request/ChatMessageRequest.java
  src/main/java/com/ll/FlexGym/domain/ChatMessage/entity/ChatMessage.java
  src/main/java/com/ll/FlexGym/domain/ChatMessage/entity/ChatMessageType.java
  src/main/java/com/ll/FlexGym/domain/ChatMessage/service/ChatMessageService.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/dto/ChatRoomDto.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/entity/ChatRoom.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/service/ChatRoomService.java
  src/main/java/com/ll/FlexGym/domain/Meeting/controller/MeetingController.java
  src/main/java/com/ll/FlexGym/domain/Meeting/entity/Meeting.java
  src/main/resources/static/app.js
  src/main/resources/templates/usr/chat/room.html
Labels: feature, refactoring

#34 ref/UI 작업
  src/main/java/com/ll/FlexGym/domain/Information/controller/InformationController.java
  src/main/resources/templates/usr/chat/room.html
  src/main/resources/templates/usr/information/admin.html
  src/main/resources/templates/usr/information/info.html
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/main/home.html
  src/main/resources/templates/usr/member/join.html
Labels: refactoring

#37 feat/발신자, 수신자 메시지 위치 수정
  src/main/java/com/ll/FlexGym/domain/ChatRoom/controller/ChatRoomController.java
  src/main/resources/static/app.js
  src/main/resources/templates/usr/chat/home.html
  src/main/resources/templates/usr/chat/newRoom.html
  src/main/resources/templates/usr/chat/room.html
Labels: feature, refactoring

#39 Feat/information 게시글 등록 폼 페이지 구현
  src/main/java/com/ll/FlexGym/domain/Information/controller/InformationController.java
  src/main/java/com/ll/FlexGym/domain/Information/repository/InformationRepository.java
  src/main/java/com/ll/FlexGym/domain/Information/service/InformationService.java
  src/main/resources/templates/usr/information/admin.html
  src/main/resources/templates/usr/information/adminToInfo_form.html
  src/main/resources/templates/usr/information/info.html
Labels: feature

#40 Feat/community cate classfication(카테고리 분류)
  src/main/java/com/ll/FlexGym/domain/Board/controller/BoardController.java
  src/main/java/com/ll/FlexGym/domain/Board/repository/BoardRepository.java
  src/main/java/com/ll/FlexGym/domain/Board/service/BoardService.java
  src/main/java/com/ll/FlexGym/global/init/NotProd.java
  src/main/resources/templates/usr/board/board_detail.html
  src/main/resources/templates/usr/board/board_form.html
  src/main/resources/templates/usr/board/board_list.html
Labels: feature

#44 Feat/meeting participant 강퇴 기능 초기 작업
  src/main/java/com/ll/FlexGym/domain/ChatMember/repository/ChatMemberRepository.java
  src/main/java/com/ll/FlexGym/domain/ChatMember/service/ChatMemberService.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/service/ChatRoomService.java
  src/main/java/com/ll/FlexGym/domain/Meeting/MeetingForm.java
  src/main/java/com/ll/FlexGym/domain/Meeting/controller/MeetingController.java
  src/main/java/com/ll/FlexGym/domain/Meeting/entity/Meeting.java
  src/main/java/com/ll/FlexGym/domain/Meeting/service/MeetingService.java
  src/main/java/com/ll/FlexGym/global/init/NotProd.java
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/meeting/detail.html
  src/main/resources/templates/usr/meeting/form.html
  src/main/resources/templates/usr/meeting/list.html
  src/main/resources/templates/usr/meeting/manage.html
Labels: feature

#47 Feat/information Status에 따른 admin, info 출력
  src/main/java/com/ll/FlexGym/domain/Information/controller/InformationController.java
  src/main/java/com/ll/FlexGym/domain/Information/entity/InfoStatus.java
  src/main/java/com/ll/FlexGym/domain/Information/entity/Information.java
  src/main/java/com/ll/FlexGym/domain/Information/repository/InformationRepository.java
  src/main/java/com/ll/FlexGym/domain/Information/service/InformationService.java
  src/main/resources/templates/usr/information/adminToInfo_form.html
  src/main/resources/templates/usr/information/info.html
Labels: feature

#49 feat:home, layout 공동작업
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/main/home.html
Labels: feature

#50 feat/참가자목록 조회 - 초기구현
  src/main/java/com/ll/FlexGym/domain/ChatMember/service/ChatMemberService.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/controller/ChatRoomController.java
  src/main/resources/static/app.js
  src/main/resources/templates/usr/chat/memberList.html
  src/main/resources/templates/usr/chat/room.html
Labels: feature

#52 Feat/community comment(커뮤니티 대댓글)
  src/main/java/com/ll/FlexGym/domain/Board/controller/BoardController.java
  src/main/java/com/ll/FlexGym/domain/Board/entity/Board.java
  src/main/java/com/ll/FlexGym/domain/Board/repository/BoardRepository.java
  src/main/java/com/ll/FlexGym/domain/Board/service/BoardService.java
  src/main/java/com/ll/FlexGym/domain/Comment/controller/CommentController.java
  src/main/java/com/ll/FlexGym/domain/Comment/entity/Comment.java
  src/main/java/com/ll/FlexGym/domain/Comment/entity/CommentForm.java
  src/main/java/com/ll/FlexGym/domain/Comment/service/CommentService.java
  src/main/java/com/ll/FlexGym/global/init/NotProd.java
  src/main/resources/templates/usr/board/board_detail.html
  src/main/resources/templates/usr/main/home.html
Labels: feature

#53 ref/채팅 UI 버그 수정
  src/main/resources/templates/usr/chat/room.html
Labels: bug, refactoring

#55 feat/meeting 참여자 강퇴 기능 구현
  src/main/java/com/ll/FlexGym/domain/ChatMember/entity/ChatMember.java
  src/main/java/com/ll/FlexGym/domain/ChatMember/entity/ChatMemberType.java
  src/main/java/com/ll/FlexGym/domain/ChatRoom/service/ChatRoomService.java
  src/main/java/com/ll/FlexGym/domain/Meeting/controller/MeetingController.java
  src/main/resources/templates/usr/meeting/detail.html
  src/main/resources/templates/usr/meeting/manage.html
Labels: feature

#58 Feat/information UI작업 완료
  src/main/java/com/ll/FlexGym/domain/Favorite/entity/Favorite.java
  src/main/java/com/ll/FlexGym/domain/Favorite/repository/FavoriteRepository.java
  src/main/java/com/ll/FlexGym/domain/Information/entity/Information.java
  src/main/java/com/ll/FlexGym/domain/Information/service/InformationService.java
  src/main/java/com/ll/FlexGym/domain/youtube/service/YoutubeService.java
  src/main/java/com/ll/FlexGym/global/init/NotProd.java
  src/main/resources/templates/usr/information/admin.html
  src/main/resources/templates/usr/information/info.html
Labels: bug, feature

#59 feat/마이페이지UI, 각종 List 추가
  src/main/java/com/ll/FlexGym/domain/Board/controller/BoardController.java
  src/main/java/com/ll/FlexGym/domain/Board/repository/BoardRepository.java
  src/main/java/com/ll/FlexGym/domain/Board/service/BoardService.java
  src/main/java/com/ll/FlexGym/domain/BoardLike/controller/BoardLikeController.java
  src/main/java/com/ll/FlexGym/domain/BoardLike/repository/BoardLikeRepository.java
  src/main/java/com/ll/FlexGym/domain/BoardLike/service/BoardLikeService.java
  src/main/java/com/ll/FlexGym/domain/Comment/controller/CommentController.java
  src/main/java/com/ll/FlexGym/domain/Comment/entity/CommentForm.java
  src/main/java/com/ll/FlexGym/domain/Comment/repository/CommentRepository.java
  src/main/java/com/ll/FlexGym/domain/Comment/service/CommentService.java
  src/main/java/com/ll/FlexGym/domain/Meeting/controller/MeetingController.java
  src/main/java/com/ll/FlexGym/domain/Meeting/repository/MeetingRepository.java
  src/main/java/com/ll/FlexGym/domain/Meeting/service/MeetingService.java
  src/main/java/com/ll/FlexGym/domain/Member/controller/MemberController.java
  src/main/java/com/ll/FlexGym/domain/Member/repository/MemberRepository.java
  src/main/resources/static/app.js
  src/main/resources/templates/usr/board/myBoardLike_list.html
  src/main/resources/templates/usr/board/myBoard_list.html
  src/main/resources/templates/usr/chat/room.html
  src/main/resources/templates/usr/comment/myComment_list.html
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/main/home.html
  src/main/resources/templates/usr/meeting/myMeeting_list.html
  src/main/resources/templates/usr/member/me.html
Labels: bug, feature, refactoring

#65 Feat/information 좋아요구현
  src/main/java/com/ll/FlexGym/domain/Favorite/controller/FavoriteController.java
  src/main/java/com/ll/FlexGym/domain/Favorite/entity/Favorite.java
  src/main/java/com/ll/FlexGym/domain/Favorite/repository/FavoriteRepository.java
  src/main/java/com/ll/FlexGym/domain/Favorite/service/FavoriteService.java
  src/main/java/com/ll/FlexGym/domain/Information/controller/InformationController.java
  src/main/java/com/ll/FlexGym/domain/Information/entity/Information.java
  src/main/java/com/ll/FlexGym/domain/Information/service/InformationService.java
  src/main/java/com/ll/FlexGym/domain/Member/entitiy/Member.java
  src/main/resources/templates/usr/information/admin.html
  src/main/resources/templates/usr/information/info.html
Labels: bug, feature

#64 feat/meeting 모임 리스트 페이징 구현/ UI 수정 작업
  src/main/java/com/ll/FlexGym/domain/ChatRoom/controller/ChatRoomController.java
  src/main/java/com/ll/FlexGym/domain/Meeting/controller/MeetingController.java
  src/main/java/com/ll/FlexGym/domain/Meeting/entity/Meeting.java
  src/main/java/com/ll/FlexGym/domain/Meeting/repository/MeetingRepository.java
  src/main/java/com/ll/FlexGym/domain/Meeting/service/MeetingService.java
  src/main/java/com/ll/FlexGym/global/init/NotProd.java
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/meeting/chatMembers.html
  src/main/resources/templates/usr/meeting/detail.html
  src/main/resources/templates/usr/meeting/list.html
Labels: feature, refactoring

#63 Community 페이징 처리
  src/main/java/com/ll/FlexGym/domain/Board/controller/BoardController.java
  src/main/java/com/ll/FlexGym/domain/Board/repository/BoardRepository.java
  src/main/java/com/ll/FlexGym/domain/Board/service/BoardService.java
  src/main/resources/templates/usr/board/board_list.html
Labels: feature

#67 Feat/information favorite fix
  src/main/java/com/ll/FlexGym/domain/Information/controller/InformationController.java
  src/main/resources/templates/usr/information/admin.html
  src/main/resources/templates/usr/information/info.html
Labels: bug

#68 feat:마이페이지에서 즐겨찾기user1버튼을 눌렀을 때 해당 유저에 대한 좋아요 목록 확인
  src/main/java/com/ll/FlexGym/domain/Favorite/controller/FavoriteController.java
  src/main/java/com/ll/FlexGym/domain/Favorite/repository/FavoriteRepository.java
  src/main/java/com/ll/FlexGym/domain/Favorite/service/FavoriteService.java
  src/main/java/com/ll/FlexGym/domain/Information/controller/InformationController.java
  src/main/java/com/ll/FlexGym/domain/Information/service/InformationService.java
  src/main/resources/templates/usr/member/me.html
Labels: feature

#76 ref/로고 버그 수정
  src/main/java/com/ll/FlexGym/domain/Board/service/BoardService.java
  src/main/java/com/ll/FlexGym/domain/BoardLike/service/BoardLikeService.java
  src/main/java/com/ll/FlexGym/domain/Comment/service/CommentService.java
  src/main/java/com/ll/FlexGym/domain/Meeting/service/MeetingService.java
  src/main/java/com/ll/FlexGym/domain/Member/controller/MemberController.java
  src/main/resources/templates/usr/chat/room.html
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/member/me.html
Labels: bug

#78 Meeting 모임 등록 폼/ 참여자 리스트 UI 작업
  src/main/resources/templates/usr/meeting/chatMembers.html
  src/main/resources/templates/usr/meeting/detail.html
  src/main/resources/templates/usr/meeting/form.html
  src/main/resources/templates/usr/meeting/list.html
Labels: enhancement

#80 ref/url수정
  src/main/java/com/ll/FlexGym/domain/Board/controller/BoardController.java
  src/main/java/com/ll/FlexGym/domain/BoardLike/controller/BoardLikeController.java
  src/main/java/com/ll/FlexGym/domain/Comment/controller/CommentController.java
  src/main/java/com/ll/FlexGym/domain/Information/controller/InformationController.java
  src/main/java/com/ll/FlexGym/domain/Meeting/controller/MeetingController.java
  src/main/java/com/ll/FlexGym/domain/home/HomeController.java
Labels: bug

#82 bug/cors버그 수정
  src/main/java/com/ll/FlexGym/global/config/WebSocketConfig.java
Labels: bug

#86 Feat/main favorite UI 메인페이지 좋아요기준 영상 출력
  src/main/java/com/ll/FlexGym/domain/Favorite/repository/FavoriteRepository.java
  src/main/java/com/ll/FlexGym/domain/Favorite/service/FavoriteService.java
  src/main/java/com/ll/FlexGym/domain/Information/controller/InformationController.java
  src/main/java/com/ll/FlexGym/domain/Information/service/InformationService.java
  src/main/java/com/ll/FlexGym/domain/home/HomeController.java
  src/main/java/com/ll/FlexGym/global/config/WebSocketConfig.java
  src/main/java/com/ll/FlexGym/global/init/NotProd.java
  src/main/resources/templates/usr/information/info.html
  src/main/resources/templates/usr/main/home.html
Labels: feature

#89 Feat/information bug fix
  src/main/java/com/ll/FlexGym/domain/Favorite/controller/FavoriteController.java
  src/main/resources/templates/usr/main/home.html
Labels: bug

#92 카카오 로그인 bug fix
  src/main/resources/application-secret.yml.default
  src/main/resources/application.yml
Labels: bug

#91 feat/검색 추가
  src/main/java/com/ll/FlexGym/domain/Board/controller/BoardController.java
  src/main/java/com/ll/FlexGym/domain/Board/repository/BoardRepository.java
  src/main/java/com/ll/FlexGym/domain/Board/service/BoardService.java
  src/main/java/com/ll/FlexGym/domain/Meeting/controller/MeetingController.java
  src/main/java/com/ll/FlexGym/domain/Meeting/entity/SearchQuery.java
  src/main/java/com/ll/FlexGym/domain/Meeting/repository/MeetingRepository.java
  src/main/java/com/ll/FlexGym/domain/Meeting/service/MeetingService.java
  src/main/resources/templates/usr/board/board_detail.html
  src/main/resources/templates/usr/board/board_form.html
  src/main/resources/templates/usr/board/board_list.html
  src/main/resources/templates/usr/board/popular_board_list.html
  src/main/resources/templates/usr/chat/room.html
  src/main/resources/templates/usr/meeting/list.html
Labels: feature

#98 bug/oauthURL 버그 수정
  src/main/resources/application-prod.yml
Labels: bug
